displayName=Scaper
author=Deafpie
description=Link your OSRS account to your clan's Discord server via Scaper bot. Tracks skills, boss KC, loot, inventory, equipment, location, and more.
tags=clan,discord,link,scaper,tracking
plugins=com.scaperplugin.ScaperPlugin
